### ISSUE TITLE
Contribute fig.yml to launch APITools and Redis

### ISSUE THREAD

**Issue by mingfang** [APItools/monitor#17]
Below is a small fig.yml that I use to launch APITools and Redis.
Hope it can help others get started more quickly(assuming they already have fig installed).

```
apitools:
  image: quay.io/3scale/apitools
  ports:
    - "7071:7071"
    - "10002:10002"
  links:
    - redis:db

redis:
  image: redis
```
